[workspace]
members = ["get-lxc", "core"]
resolver = "2"

[profile.release]
panic = "unwind"

[profile.thin]
inherits = "release"
panic = "abort"
strip = true
lto = "thin"

[profile.fat]
inherits = "thin"
lto = "fat"
opt-level = "z"
