#!/usr/bin/env bash
set -ex
#-----------------
cat_gui_readme() {
    cat >docker-readme.md <<-EOF
# ${Container_name}

## How to run it?

\`\`\`sh
# install docker
if [ -z "\$(command -v docker)" ]; then
    apt update
    apt install docker.io
    # If your host architecture is not ${arch}, then install qemu & binfmt-support.
    apt install qemu-user-static
fi

# 5903 is the host vnc port
# 5902 is the container vnc port
# 36080 is the container novnc port
docker run \\
    -it \\
    --shm-size 512m \\
    -p 5903:5902 \\
    -p 36081:36080 \\
    --name ${Container_name} \\
    -e LANG=en_US.UTF-8 \\
    ${repo}

# optional: bind audio server
# host cmd: pactl load-module module-native-protocol-unix socket=/path/to/src.socket
# docker args: -v /path/to/src.socket:/path/to/target.socket \\
# -e PULSE_SERVER=unix:/path/to/target.socket

\`\`\`

## How to start vnc?

\`\`\`sh
    docker exex -it ${Container_name} zsh
\`\`\`

The default user is root.

After entering the container, you can create a new user, and then switch to it.

Finally, run the following commands.

\`\`\`sh
    startvnc
\`\`\`

or

\`\`\`
    startx11vnc
\`\`\`

or

\`\`\`sh
    novnc
\`\`\`

Note:

If you want to use novnc, then open your browser, and type the address:

\`\`\`
http://localhost:36081
\`\`\`

If you want to use tiger/x11vnc, then open vnc viewer, then type the address:

\`\`\`
localhost:5903
\`\`\`
EOF
}
cat_nogui_readme() {
    cat >docker-readme.md <<-EOF
# ${Container_name}

## How to run it?

\`\`\`sh
docker run \\
    -it \\
    --name ${Container_name} \\
    ${repo}
\`\`\`

## How to exec shell?

\`\`\`sh
docker exec -it ${Container_name} ${LOGIN_SHELL}
\`\`\`
EOF
}

cat_code_readme() {
    cat >docker-readme.md <<-EOF
# ${Container_name}

## How to build and run it?

### Full

#### create a dockerfile

\`\`\`sh
_TMP=\$TMPDIR/tmp/code-docker
mkdir -pv \$_TMP
cd \$_TMP
\`\`\`


\`\`\`Dockerfile
cat >>init.dockerfile<<-'EndOfDockerfile'
$(cat "$dir"/../code/init/init.dockerfile)
EndOfDockerfile
\`\`\`

#### set env

\`\`\`sh
$(cat "$dir"/../code/init/0.set)
\`\`\`

#### build container

\`\`\`sh
$(cat "$dir"/../code/init/1.build)
\`\`\`

#### run

\`\`\`sh
$(cat "$dir"/../code/init/2.run)
\`\`\`

### Lite

Do we really have to use such tedious steps as above?

No! Although the steps are similar to those above, they are much simpler.

#### copy the necessary folders to the temporary directory

\`\`\`sh
TMP=\$TMPDIR/tmp/code-docker
mkdir -pv \$TMP
docker run -t --rm ${repo} sh -c "cp -rfv /root/init \$_TMP"
cd init
\`\`\`

#### set env

\`\`\`sh
editor 0.set

. 0.set
\`\`\`

#### build

\`\`\`sh
. 1.build
\`\`\`

#### run

\`\`\`
. 2.run
\`\`\`

EOF
    # cat "$dir"/../code/init/0.set >>docker-readme.md
    # echo '```' >>docker-readme.md

    # printf "%s\n" \
    #     '#### build container' \
    #     '' \
    #     '```sh' \
    #     >>docker-readme.md
    # cat "$dir"/../code/init/1.build >>docker-readme.md
    # echo '```' >>docker-readme.md

    # printf "%s\n" \
    #     '#### run' \
    #     '' \
    #     '```sh' \
    #     >>docker-readme.md
    # cat "$dir"/../code/init/2.run >>docker-readme.md
    # echo '```' >>docker-readme.md

    # printf "%s\n" \
    #     '' \
    #     '### Lite' \
    #     '' \
    #     'Do we really have to use such tedious steps as above?" \
    #     "" \
    #     "No! No need.' \
    #     '```sh' \
    #     "docker run -t --rm ${repo} sh -c 'cp /root/'" \
    #     >>docker-readme.md

}

cat_build_info_title() {
    cat >build_info_title.md <<-EOF

## ${Container_name}.toml

\`\`\`toml
EOF
    cat build_info_title.md >>docker-readme.md
}

cat_go_readme() {
    cat >go-example.md <<-EOF

## example

\`\`\`sh
docker run \\
    -t \\
    --rm \\
    -v "\$PWD"/go-project:/app \\
    -w /app \\
    -e GOOS=linux \\
    -e CGO_ENABLED=0 \\
    ${repo} \\
    go build -trimpath --ldflags "-s -w -buildid=" -v -o main.bin
\`\`\`
EOF

    cat go-example.md >>docker-readme.md

    printf "%s\n" \
        "" \
        '## readme.go' \
        '```go' \
        >>docker-readme.md

    cat "$dir"/go.go >>docker-readme.md
    echo '```' >>docker-readme.md
}

cat_rust_readme() {
    cp -v "$dir"/rust.md ./rs-example.md
    # cake233/rust-amd64
    sed \
        -e "s@cake233/rust-amd64@${repo}@g" \
        -i rs-example.md
    cat rs-example.md >>docker-readme.md
}

case ${X11} in
false)
    case "$name" in
    code) cat_code_readme ;;
    *) cat_nogui_readme ;;
    esac

    case "$name" in
    go) cat_go_readme ;;
    rust) cat_rust_readme ;;
    esac
    cat_build_info_title
    ;;
true)
    cat_gui_readme
    cat_build_info_title
    ;;
esac

cat ./i.toml >>docker-readme.md
echo '```' >>docker-readme.md
