# This is a basic workflow to help you get started with Actions
name: Ubuntu-dev_amd64-xfce

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    #container: multiarch/qemu-user-static:x86_64-aarch64
    #env:
    #REPO: ${{ secrets.DEBUG_REPO }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      - name: git clone tmoe-linux
        run: |
          cd ${HOME}
          git clone --depth=1 https://github.com/2moe/tmoe-linux git || git clone --depth=1 git://github.com/2moe/tmoe-linux git

      - name: docker build
        continue-on-error: true
        run: |
          cd ${HOME}/git/share/docker-build/amd64/ubuntu-dev/xfce
          pwd
          sed -i '/install-gui.sh/d' Dockerfile
          docker build -t u2 .
          at now + 2 minutes<<<"docker stop u2;docker kill u2"
          docker run -t --name u2 u2 /bin/zsh

      - name: docker export
        continue-on-error: true
        run: |
          cd /tmp
          docker export u2 > ubuntu-amd64.tar
          ls -lah
          mkdir u2
          cd u2
          tar -xvf ../ubuntu-amd64.tar 2>/dev/null

      - name: view zsh file
        run: ls -lah /tmp/u2/root/.cache/gitstatus
