# This is a basic workflow to help you get started with Actions
name: Ubuntu-dev_amd64-xfce

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    #container: multiarch/qemu-user-static:x86_64-aarch64
    #env:
    #REPO: ${{ secrets.DEBUG_REPO }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

      - name: Install qemu user
        run: |
          #sudo apt update
          #sudo apt install -y qemu-user-static curl
          #QEMU_REPO='https://ftp.debian.org/debian/pool/main/q/qemu'
          #QEMU_VERSION=$(curl -L ${QEMU_REPO} | grep 'qemu-user-static' | grep 'bpo.*deb' | grep $(dpkg --print-architecture) | tail -n 1 | awk -F 'a href=' '{print $2}' | cut -d '"' -f 2)
          #QEMU_URL="${QEMU_REPO}/${QEMU_VERSION}"
          #curl -L -o qemu-user-static_amd64.deb ${QEMU_URL}
          #sudo apt install -y ./qemu-user-static_amd64.deb || sudo dpkg -i qemu-user-static_amd64.deb
          qemu-aarch64-static --version 2>&1 >qemu-version.txt
          cat qemu-version.txt

      #- name: Set up Docker Buildx
      #  id: buildx
      #  uses: docker/setup-buildx-action@v1
      #  with:
      #    version: latest
      - name: run arm64 container
        run: docker run -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static arm64v8/alpine:latest /bin/ash
        # 在--platform后面指定需要兼容的平台列表
