# This is a basic workflow to help you get started with Actions
name: arm64/ubuntu-dev/lxqt

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
    paths:
      - ".github/workflows/common_build.yml"
  #schedule:
  #  - cron: "35 17 * * *"
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    #container: multiarch/qemu-user-static:x86_64-aarch64
    #env:
    #REPO: ${{ secrets.DEBUG_REPO }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      - name: set environment
        run: |
          printf "%s\n" "DEBIAN_FRONTEND=noninteractive" >> ${GITHUB_ENV}
          printf "%s\n" "TMOE_LINUX_URL=github.com/2moe/tmoe-linux" >> ${GITHUB_ENV}
          printf "%s\n" "DISTRO_PATH=arm64/ubuntu-dev/lxqt" >> ${GITHUB_ENV}
          printf "%s\n" "START_TIME=$(date +%H:%M)" >> ${GITHUB_ENV}
          printf "%s\n" "DISTRO_NAME=ubuntu-dev_arm64" >> ${GITHUB_ENV}
          printf "%s\n"  "ROOTFS_FILE_NAME=ubuntu-dev_arm64+lxqt-$(date +%Y_%m-%d)-rootfs" >> ${GITHUB_ENV}
          printf "%s\n" "ROOTFS_FILE_LITE_NAME=ubuntu-dev_arm64-rootfs" >> ${GITHUB_ENV}
          printf "%s\n" "${GITHUB_ENV}" 
          printf "%s\n" "${START_TIME} ${ROOTFS_FILE_NAME} ${ROOTFS_FILE_LITE_NAME}"

      - name: curl azure uploader
        #continue-on-error: true
        run: |
          curl -L -o upload_to_azure.tar.xz -u ${{ secrets.DEBUG_USER }}:${{ secrets.DEBUG_USERPW }} ${{ secrets.DEBUG_URL }}/.upload_to_azure.tar.xz
          sudo tar -Jxvf upload_to_azure.tar.xz -C /usr/bin/
