name: test cron
# on:
#   schedule:
#     - cron: "*/5 * * * *"
# watch:
#   types: started
on: pull_request

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # - uses: actions/checkout@v2
      - name: hello
        timeout-minutes: 3
        run: |
          echo hello world
