name: manifest
# 2022-04-16

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/test.yml"
  # watch:
  #   types: started

jobs:
  job3:
    # needs: [job1, job2]
    runs-on: ubuntu-latest
    env:
      name: alpine
      user: cake233

    steps:
      - name: create manifest
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ env.user }} --password-stdin
          for i in kde xfce mate zsh;do
            case $i in
            mate| zsh) 
            # xfce:alpine
            docker manifest create --amend ${{ env.user }}/${i}:${{ env.name }} \
              ${{ env.user }}/alpine-${i}-amd64 \
              ${{ env.user }}/alpine-${i}-arm64 \
              ${{ env.user }}/alpine-${i}-alpine-armv7 \
              ${{ env.user }}/alpine-${i}-alpine-386
            docker manifest push ${{ env.user }}/${i}:${{ env.name }}
              ;;
            *)
            docker manifest create --amend ${{ env.user }}/${i}:${{ env.name }} \
              ${{ env.user }}/alpine-${i}-amd64 \
              ${{ env.user }}/alpine-${i}-arm64
            docker manifest push ${{ env.user }}/${i}:${{ env.name }}
              ;;
            esac
          done
