name: manifest
# 2022-04-16

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/test.yml"
  # watch:
  #   types: started

jobs:
  job3:
    # needs: [job1, job2]
    runs-on: ubuntu-latest
    env:
      user: cake233

    steps:
      - name: arch manifest
        env:
          name: arch
        run: |
          # name=arch
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ env.user }} --password-stdin
          # for i in kde cutefish xfce mate zsh;do
          i=cutefish
          docker manifest create --amend ${{ env.user }}/${i}:${{ env.name }} \
              ${{ env.user }}/${{ env.name }}-${i}-amd64 \
              ${{ env.user }}/${{ env.name }}-${i}-arm64 \
              ${{ env.user }}/${{ env.name }}-${i}-armv7
          docker manifest push ${{ env.user }}/${i}:${{ env.name }}
