name: test
# 2022-03-24

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/test.yml"
  # watch:
  #   types: started

jobs:
  job1:
    # needs: [job0, job1]
    runs-on: ${{ matrix.os }}
    env:
      # name: ${{ matrix.name }}
      name: arch
      user: cake233
      platform: ${{ matrix.platform }}
      arch: ${{ matrix.arch }}
      zstd_level: 12

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            tag: base
            arch: arm64
            platform: "linux/arm64"

    # repeat...
    steps:
      - uses: actions/checkout@v2
        with:
          # repository: "2moe/xxx"
          ref: "master"
          fetch-depth: 1

      - name: get architecture
        env:
          TARGETARCH: ${{ matrix.arch }}
        run: bash docker/assets/get_arch

      - name: get container os & set global env
        env:
          tag: ${{ matrix.tag }}
        run: bash docker/action/get_container_os

      - name: set up qemu-user & binfmt
        id: qemu
        uses: docker/setup-qemu-action@v1
        if: matrix.arch != 'amd64' && matrix.arch != 'i386'
        with:
          image: tonistiigi/binfmt:latest
          platforms: ${{ matrix.platform }}

      - name: run arch arm64
        run: |
          cd docker/arch
          docker build -t archarm-202203 -f ../tmp.dockerfile  .
