name: manifest
# 2022-04-16

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/test.yml"
  # watch:
  #   types: started

jobs:
  job3:
    # needs: [job1, job2]
    runs-on: ubuntu-latest
    env:
      user: cake233

    steps:
      - name: swift manifest
        env:
          name: swift
        run: |
          # name=swift
          TODAY=$(date -u +%Y-%m-%d)
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ env.user }} --password-stdin
          for i in latest ubuntu ${TODAY};do
            docker manifest create --amend ${{ env.user }}/${{ env.name }}:${i} \
            ${{ env.user }}/${{ env.name }}-amd64 \
            ${{ env.user }}/${{ env.name }}-arm64
            docker manifest push ${{ env.user }}/${{ env.name }}:${i}
          done

      - name: dotnet manifest
        env:
          name: dotnet
        run: |
          # name=dotnet
          TODAY=$(date -u +%Y-%m-%d)
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ env.user }} --password-stdin
          for i in latest ${TODAY};do
            docker manifest create --amend ${{ env.user }}/${{ env.name }}:${i} \
            ${{ env.user }}/${{ env.name }}-amd64 \
            ${{ env.user }}/${{ env.name }}-arm64
            docker manifest push ${{ env.user }}/${{ env.name }}:${i}
          done
